"""Initial schema (§4.3): all tables, hypertables, immutability triggers.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

import os

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


HYPERTABLES = ("price_bars", "features")
IMMUTABLE_TABLES = ("fundamentals_asfiled", "decision_commitments")


def _timescale() -> None:
    """Hypertables need TimescaleDB. Plain Postgres is allowed only with
    STORE_ALLOW_PLAIN_POSTGRES=1 (local test clusters); compose and CI run TimescaleDB."""
    bind = op.get_bind()
    available = bind.execute(
        sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb'")
    ).first()
    if available is None:
        if os.environ.get("STORE_ALLOW_PLAIN_POSTGRES") == "1":
            return
        raise RuntimeError("timescaledb extension is not available on this server")
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    for table in HYPERTABLES:
        op.execute(
            f"SELECT create_hypertable('{table}', by_range('event_time', INTERVAL '30 days'))"
        )


def upgrade() -> None:
    op.execute(
        """
        CREATE FUNCTION reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is insert-only (%)', TG_TABLE_NAME, TG_OP;
        END $$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_scores",
        sa.Column("agent", sa.Text(), nullable=False),
        sa.Column("model_served", sa.Text(), nullable=False),
        sa.Column("window", sa.Text(), nullable=False),
        sa.Column("brier", sa.Double(), nullable=True),
        sa.Column("ic", sa.Double(), nullable=True),
        sa.Column("hit_rate", sa.Double(), nullable=True),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "agent", "model_served", "window", "computed_at", name="uq_agent_scores"
        ),
    )
    op.create_table(
        "feed_health",
        sa.Column("feed", sa.Text(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("feed"),
    )
    op.create_table(
        "news_items",
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column("item_id", sa.Text(), nullable=False),
        sa.Column("security_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("body_hash", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("publisher", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.UniqueConstraint("item_id", "source_version", name="uq_news_items"),
    )
    op.create_index("ix_news_items_avail", "news_items", ["available_at"], unique=False)
    op.create_index(
        "ix_news_items_sids", "news_items", ["security_ids"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("config_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "securities",
        sa.Column("security_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("cik", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column("listed_from", sa.Date(), nullable=True),
        sa.Column("listed_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("security_id"),
        sa.UniqueConstraint("cik", "ticker", name="uq_securities_cik_ticker"),
    )
    op.create_table(
        "agent_verdicts",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("agent", sa.Text(), nullable=False),
        sa.Column("verdict", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Double(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.UniqueConstraint("run_id", "security_id", "agent", name="uq_agent_verdicts"),
    )
    op.create_table(
        "committee_decisions",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("pooled_p", sa.Double(), nullable=False),
        sa.Column("dispersion", sa.Double(), nullable=False),
        sa.Column("target_weight", sa.Double(), nullable=False),
        sa.Column("cio_action", sa.Text(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.UniqueConstraint("run_id", "security_id", name="uq_committee_decisions"),
    )
    op.create_table(
        "decision_commitments",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column(
            "committed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "features",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column("feature_set_version", sa.Text(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.UniqueConstraint(
            "security_id", "event_time", "feature_set_version", "source_version", name="uq_features"
        ),
    )
    op.create_index(
        "ix_features_sid_avail", "features", ["security_id", "available_at"], unique=False
    )
    op.create_table(
        "fundamentals_asfiled",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column("concept", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("fiscal_period", sa.Text(), nullable=True),
        sa.Column("form", sa.Text(), nullable=True),
        sa.Column("value", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.UniqueConstraint(
            "security_id",
            "concept",
            "unit",
            "period_start",
            "period_end",
            "source_version",
            name="uq_fundamentals_asfiled",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_fundamentals_asfiled_sid_avail",
        "fundamentals_asfiled",
        ["security_id", "available_at"],
        unique=False,
    )
    op.create_table(
        "gate_decisions",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.UniqueConstraint("run_id", "security_id", name="uq_gate_decisions"),
    )
    op.create_table(
        "insider_txns",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column("accession", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("filer", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("officer_title", sa.Text(), nullable=True),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("acquired", sa.Boolean(), nullable=False),
        sa.Column("shares", sa.Double(), nullable=False),
        sa.Column("price", sa.Double(), nullable=True),
        sa.Column("post_holdings", sa.Double(), nullable=True),
        sa.Column("is_10b5_1", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.UniqueConstraint("accession", "seq", "source_version", name="uq_insider_txns"),
    )
    op.create_index(
        "ix_insider_txns_sid_avail", "insider_txns", ["security_id", "available_at"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("broker_order_id", sa.Text(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("qty", sa.Double(), nullable=False),
        sa.Column("limit_price", sa.Double(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.PrimaryKeyConstraint("broker_order_id"),
    )
    op.create_table(
        "outcomes",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("horizon", sa.Integer(), nullable=False),
        sa.Column("fwd_return", sa.Double(), nullable=False),
        sa.Column("sector_fwd_return", sa.Double(), nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.UniqueConstraint("run_id", "security_id", "horizon", name="uq_outcomes"),
    )
    op.create_table(
        "price_bars",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column("open", sa.Double(), nullable=False),
        sa.Column("high", sa.Double(), nullable=False),
        sa.Column("low", sa.Double(), nullable=False),
        sa.Column("close", sa.Double(), nullable=False),
        sa.Column("volume", sa.Double(), nullable=False),
        sa.Column("feed", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.UniqueConstraint("security_id", "event_time", "source_version", name="uq_price_bars"),
    )
    op.create_index(
        "ix_price_bars_sid_avail", "price_bars", ["security_id", "available_at"], unique=False
    )
    op.create_table(
        "universe_snapshots",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("mcap_usd", sa.Double(), nullable=True),
        sa.Column("mcap_tier", sa.Text(), nullable=True),
        sa.Column("adv_usd", sa.Double(), nullable=True),
        sa.Column("price", sa.Double(), nullable=True),
        sa.Column("score", sa.Double(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
        ),
        sa.UniqueConstraint(
            "snapshot_date", "security_id", "source_version", name="uq_universe_snapshots"
        ),
    )
    op.create_index(
        "ix_universe_snapshots_sid_avail",
        "universe_snapshots",
        ["security_id", "available_at"],
        unique=False,
    )
    op.create_table(
        "fills",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("broker_order_id", sa.Text(), nullable=False),
        sa.Column("fill_id", sa.Text(), nullable=False),
        sa.Column("qty", sa.Double(), nullable=False),
        sa.Column("price", sa.Double(), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("slippage_bps", sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_order_id"],
            ["orders.broker_order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("fill_id"),
    )
    # ### end Alembic commands ###
    _timescale()
    for table in IMMUTABLE_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION reject_mutation()"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fills")
    op.drop_index("ix_universe_snapshots_sid_avail", table_name="universe_snapshots")
    op.drop_table("universe_snapshots")
    op.drop_index("ix_price_bars_sid_avail", table_name="price_bars")
    op.drop_table("price_bars")
    op.drop_table("outcomes")
    op.drop_table("orders")
    op.drop_index("ix_insider_txns_sid_avail", table_name="insider_txns")
    op.drop_table("insider_txns")
    op.drop_table("gate_decisions")
    op.drop_index("ix_fundamentals_asfiled_sid_avail", table_name="fundamentals_asfiled")
    op.drop_table("fundamentals_asfiled")
    op.drop_index("ix_features_sid_avail", table_name="features")
    op.drop_table("features")
    op.drop_table("decision_commitments")
    op.drop_table("committee_decisions")
    op.drop_table("agent_verdicts")
    op.drop_table("securities")
    op.drop_table("runs")
    op.drop_index("ix_news_items_sids", table_name="news_items", postgresql_using="gin")
    op.drop_index("ix_news_items_avail", table_name="news_items")
    op.drop_table("news_items")
    op.drop_table("feed_health")
    op.drop_table("agent_scores")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION reject_mutation()")
